apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    app: {{ .Values.metadata.labels.app }}
    part-of: {{ .Values.metadata.labels.partOf }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}
        part-of: {{ .Values.metadata.labels.partOf }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        
        {{- if .Values.spec.containers.readinessProbe }}
        readinessProbe:
{{ toYaml .Values.spec.containers.readinessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.spec.containers.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.spec.containers.livenessProbe | indent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.spec.containers.resources | nindent 10 }}
        securityContext:
          {{- toYaml .Values.spec.containers.securityContext | nindent 10 }}
        volumeMounts:
          {{- toYaml .Values.spec.containers.volumeMounts | nindent 10 }}
        env: 
          {{- toYaml .Values.spec.containers.env | nindent 10 }}

      volumes:
        {{- toYaml .Values.spec.volumes | nindent 8 }}
      